### PR TITLE
Created class to generate C header file from IPXACT 

### PR DESCRIPTION
**Pull request by EdwinElshoud**
The created header file is based on macro's that take the register value and get the value of a particular field of the register.

This can (also) be used in user space.

### CODE REVIEW

**Comment by vermaete** [comment]
LGTM
@oddball: can we have new release with this?

**Comment by oddball** [comment]
@vermaete I wanna look over it this weekend. But soon 👍

**Comment by oddball** [comment]
LGTM

**Comment by oddball** [comment]
@EdwinElshoud Thanks for this! 👍 

Added a compilation and execution of your example.c on CircleCI

Released https://pypi.org/project/ipxact2systemverilog/

Feel free to check it out, and let me know if something is wrong!

**Comment by EdwinElshoud** [comment]
Great! Thanks for the review and merge work.

Op di 30 aug. 2022 om 21:21 schreef oddball ***@***.***>

**Pull request merged**
